# -*- coding: utf-8 -*-
"""clase_15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125HsYv4Ud9KjJoietLmklMEovZnNQwzj
"""

import streamlit as st

# Título de la aplicación
st.title('Mi Primera Aplicación Web con Streamlit')
# Texto simple
st.write('Esta es una aplicación web de ejemplo utilizando Streamlit.')